export const Game = {
  version: "0.1.1",
  id: "hopkit",
  isApp: (typeof nw !== "undefined"),
  /** @type {HTMLCanvasElement} */
  canvas: null,
  /** @type {HTMLInputElement} */
  textInput: null,
  /** @type {HTMLInputElement} */
  fileInput: null,
  /** @type {CanvasRenderingContext2D} */
  ctx: null,
  lastTimestamp: 0,
  dt: 0,
  fps: 0,
  recentFps: [],
  avgFps: 0,
  recentFrameTimes: [],
  minFrameTime: 0,
  maxFrameTime: 0,
  avgFrameTime: 0,
  dpr: 1,
  gameTime: 0,
  debugText: [],
  inputs: {},
  inputsClicked: {},
  inputsReleased: {},
  keybinds: {},
  keybindsClicked: {},
  keybindsReleased: {},
  mousePos: null,
  prevMousePos: null,
  mouseVel: null,
  setCursor: (type) => {document.documentElement.style.cursor = `url('assets/textures/cursors/${type}.png') 10 5, auto`},
  loading: null,
  loadingText: "",
  textures: {},
  fonts: {},
  jsons: {},
  debugToggles: [],
  ignoreNextDebugToggle: false,
  entities: {},
};