
export function drawNineSlice(ctx, img, spritesizeX, spritesizeY, slices, posX, posY, sizeX, sizeY, offsetX, offsetY, scale) {
  const x = posX, y = posY;
  let width = sizeX, height = sizeY;
  const top = slices[0], right = slices[1], bottom = slices[2], left = slices[3];
  width -= (left * scale - left) + (right * scale - right);
  height -= (top * scale - top) + (bottom * scale - bottom);
  if (width < left + right || height < top + bottom) return;
  const middleWidth = spritesizeX - left - right;
  const middleHeight = spritesizeY - top - bottom;
  const destMiddleWidth = width - left - right;
  const destMiddleHeight = height - top - bottom;
  const textureX = offsetX;
  const textureY = offsetY;
  const lS = left * scale, rS = right * scale, tS = top * scale, bS = bottom * scale;
  const dx0 = x;
  const dx1 = x + lS;
  const dx2 = dx1 + destMiddleWidth;
  const dy0 = y;
  const dy1 = y + tS;
  const dy2 = dy1 + destMiddleHeight;
  const sx0 = textureX;
  const sx1 = textureX + left;
  const sx2 = sx1 + middleWidth;
  const sy0 = textureY;
  const sy1 = textureY + top;
  const sy2 = sy1 + middleHeight;
  ctx.drawImage(img, sx0, sy0, left, top, dx0, dy0, lS, tS);
  ctx.drawImage(img, sx1, sy0, middleWidth, top, dx1, dy0, destMiddleWidth, tS);
  ctx.drawImage(img, sx2, sy0, right, top, dx2, dy0, rS, tS);
  ctx.drawImage(img, sx0, sy1, left, middleHeight, dx0, dy1, lS, destMiddleHeight);
  ctx.drawImage(img, sx1, sy1, middleWidth, middleHeight, dx1, dy1, destMiddleWidth, destMiddleHeight);
  ctx.drawImage(img, sx2, sy1, right, middleHeight, dx2, dy1, rS, destMiddleHeight);
  ctx.drawImage(img, sx0, sy2, left, bottom, dx0, dy2, lS, bS);
  ctx.drawImage(img, sx1, sy2, middleWidth, bottom, dx1, dy2, destMiddleWidth, bS);
  ctx.drawImage(img, sx2, sy2, right, bottom, dx2, dy2, rS, bS);
};
